[package]
name = "locationdpf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.1"
ctr = "0.9.2"
num-bigint = { version = "0.4.3", features = ["rand", "serde"] }
rand = "0.8.5"
rand_core = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num = "0.4.0"
lazy_static = "1.4"
zipf = "7.0.0"
bincode = "1.3.3"
# rayon = "1.5.3"
rayon = "1.3.1"

# aes-ctr = "0.6.0"
native-tls = "0.2.10"
env_logger = "0.9.1"
futures = "0.3.24"
primal = "0.3.1"

# tokio = { version = "1.21.2", features = ["full"] }
# tokio-native-tls = "0.3.0"
# tokio-serde = {version = "0.8.0", features = ["json", "bincode"]}

# clap = "4.0.4"
clap = "2.0"
tarpc = { version = "0.21", features = ["full", "serde-transport", "tcp"]  }
tokio = { version = "0.2", features = ["full"] }
tokio-native-tls = { version = "0.1" }
tokio-serde = {version = "0.6.1", features = ["json", "bincode"]}
# env_logger = "0.6"
# primal = "0.2.3"
