mode.attribute_based_metrics.num_attributes = 1024

data_bits = 10
hist_buckets = 100

server_0 = "0.0.0.0:8000"
server_1 = "0.0.0.0:8001"

add_report_share_batch_size = 50
query_flp_batch_size = 10000
zipf_unique_buckets = 1000
zipf_exponent = 1.03
